---
abstract: 'CONNECT method'
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
build_requires:
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-Proxy-Connect-IO
provides:
  Plack::Middleware::Proxy::Connect::IO:
    file: lib/Plack/Middleware/Proxy/Connect/IO.pm
    version: '0.0100'
requires:
  Plack: '0'
  Plack::App::Proxy: '0'
  perl: '5.006'
resources:
  bugtracker: http://github.com/dex4er/perl-Plack-Middleware-Proxy-Connect-IO/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dex4er/perl-Plack-Middleware-Proxy-Connect-IO
version: '0.0100'
